### ISSUE TITLE
Connection error in proxy environment

### ISSUE THREAD

**Issue by chbussler** [postgresml/postgresml#1034]
1. I started the docker container as outlined here https://postgresml.org/docs/guides/setup/quick_start_with_docker as a docker-compose service running on a Ubuntu laptop as host. Version: `ghcr.io/postgresml/postgresml:2.7.9`
2. When executing the example: 
```
SELECT pgml.embed(
    'intfloat/e5-small',
    'passage: PostgresML is so easy!'
);
```
I am getting the following error:
```
postgresml=# SELECT pgml.embed(
postgresml(#     'intfloat/e5-small',
postgresml(#     'passage: PostgresML is so easy!'
postgresml(# );
ERROR:  Traceback (most recent call last):
  File "", line 258, in embed
  File "/var/lib/postgresml-python/pgml-venv/lib/python3.10/site-packages/sentence_transformers/SentenceTransformer.py", line 87, in __init__
    snapshot_download(model_name_or_path,
  File "/var/lib/postgresml-python/pgml-venv/lib/python3.10/site-packages/sentence_transformers/util.py", line 442, in snapshot_download
    model_info = _api.model_info(repo_id=repo_id, revision=revision, token=token)
  File "/var/lib/postgresml-python/pgml-venv/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/var/lib/postgresml-python/pgml-venv/lib/python3.10/site-packages/huggingface_hub/hf_api.py", line 1677, in model_info
    r = get_session().get(path, headers=headers, timeout=timeout, params=params)
  File "/var/lib/postgresml-python/pgml-venv/lib/python3.10/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/var/lib/postgresml-python/pgml-venv/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/var/lib/postgresml-python/pgml-venv/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/var/lib/postgresml-python/pgml-venv/lib/python3.10/site-packages/huggingface_hub/utils/_http.py", line 63, in send
    return super().send(request, *args, **kwargs)
  File "/var/lib/postgresml-python/pgml-venv/lib/python3.10/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
 ConnectionError: (MaxRetryError('HTTPSConnectionPool(host=\'huggingface.co\', port=443): Max retries exceeded with url: /api/models/intfloat/e5-small (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f1767feb310>: Failed to resolve \'huggingface.co\' ([Errno -2] Name or service not known)"))'), '(Request ID: f73abd96-7819-44a6-8ff3-f246e9068308)')

```
3. This does not happen when I execute the same on a Ubuntu host that is not behind a proxy. In that case it works flawlessly.
4. I tried without success
 - setting the environment variables `HTTP_PROXY` and `HTTPS_PROXY` in the container
 - changing docker compose to use the host network
6. I found this thread: https://github.com/huggingface/transformers/issues/17611 (just as FYI)

Any help would be appreciated so that I can run the example from behind a firewall.

**Comment by montanalow** [comment]
You'll likely need to configure your firewall to allow your database/docker host to make outbound https requests.

**Comment by chbussler** [comment]
Thanks for your quick response! The firewall on my laptop is inactive, just checked. 

Since I am within an enterprise, I have very little chance in requesting the firewall to be opened up. However, I tried to hand walk an example in Python, and the following code executes successfully on the same laptop:

```
from sentence_transformers import SentenceTransformer

model = SentenceTransformer("intfloat/e5-small-v2")

embedding = model.encode('PGML is based on PostgreSQL')
print(len(embedding))
print(embedding)
```

I infer that in principle the laptop can reach Hugging Face and download models. It was stored in the cache and it runs offline as well (without a network connection). Not sure what this tells me, I tried to find out if there is anything in the Docker or in the docker compose setup I need to change, but I could not find any hing. Just FYI.

**Comment by montanalow** [comment]
This does indeed very much appear to be the same issue you mentioned: 

https://github.com/huggingface/transformers/issues/17611

Unfortunately I cannot reproduce this, and the issue appears to be currently unresolved. We'll need to wait on a solution from upstream.
