### ISSUE TITLE
ImportError: cannot import name 'Tensor' from 'torch' (unknown location)

### ISSUE THREAD

**Issue by daimenhutchison** [postgresml/postgresml#1302]
Hi, I'm trying to setup a self-hosted installation on Rocky 9.3. I've followed the instructions, and ensured that I have the dependencies listed in the requirements.txt (and the linux version). The installation completed with no errors and I was able to create the extension fine.

I get the following error;

```sql
postgres=# SELECT pgml.transform(
    'translation_en_to_fr',
    inputs => ARRAY[
        'Welcome to the future!',
        'Where have you been all this time?'
    ]
) AS french;
ERROR:  Traceback (most recent call last):
  File "transformers.py", line 10, in <module>
  File "/usr/local/lib/python3.9/site-packages/InstructorEmbedding/__init__.py", line 1, in <module>
    from .instructor import *
  File "/usr/local/lib/python3.9/site-packages/InstructorEmbedding/instructor.py", line 8, in <module>
    from torch import Tensor, device
 ImportError: cannot import name 'Tensor' from 'torch' (unknown location)
```

I'm able to run `SELECT * FROM pgml.load_dataset('diabetes');` no problem.

And this `SELECT pgml.validate_python_dependencies();` returns;

```
Python version: 3.9.18 (main, Sep  7 2023, 00:00:00) 
[GCC 11.4.1 20230605 (Red Hat 11.4.1-2)]
Scikit-learn 1.3.2, XGBoost 2.0.2, LightGBM 4.1.0, NumPy 1.26.2
```

Not sure what to check next, would appreciate any advice.

**Comment by daimenhutchison** [comment]
I got pass this error by;

```
pip3 uninstall torch
pip3 install torch==2.0.1
```

Somehow I ended up with the wrong version. Looks like I'm in the same boat with CUDA;

```
org.jkiss.dbeaver.model.sql.DBSQLException: SQL Error [XX000]: ERROR: Traceback (most recent call last):
  File "transformers.py", line 10, in <module>
  File "/usr/local/lib/python3.9/site-packages/InstructorEmbedding/__init__.py", line 1, in <module>
    from .instructor import *
  File "/usr/local/lib/python3.9/site-packages/InstructorEmbedding/instructor.py", line 2, in <module>
    import torch
  File "/usr/local/lib64/python3.9/site-packages/torch/__init__.py", line 228, in <module>
    _load_global_deps()
  File "/usr/local/lib64/python3.9/site-packages/torch/__init__.py", line 190, in _load_global_deps
    ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
  File "/usr/lib64/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
 OSError: libcufft.so.10: cannot open shared object file: No such file or directory
 ```
 
 I was careful to follow the dependencies in the various requirements files, guess I've messed that up somewhere.

**Comment by montanalow** [comment]
Did you install the platform specific dependencies, or the generic `requirements.txt`. Complex ML dependency graphs frequently break, so we provide a complete/working frozen set per platform.

**Comment by daimenhutchison** [comment]
do you mean the requirements.linux.txt? If so, yes.
