### ISSUE TITLE
pgml.transform not working

### ISSUE THREAD

**Issue by rmunoz10** [postgresml/postgresml#1518]
Hello,
pgml.transform is not working for me. Not sure what I may be missing...

Details to reproduce below

Thanks

**Environment**
Ubuntu 22.04 LTS server
Postgres 14
DBeaver

**Steps to reproduce**
**1. Create extension**
 CREATE EXTENSION IF NOT EXISTS pgml;

**2. Run following SQL**
SELECT pgml.transform(
    task => 'text-generation',
    inputs => ARRAY[
        'Three Rings for the Elven-kings under the sky, Seven for the Dwarf-lords in their halls of stone'
    ]
) AS answer;

**3. Returns Error:**
SQL Error [XX000]: ERROR: Traceback (most recent call last):
  File "transformers.py", line 10, in <module>
 ModuleNotFoundError: No module named 'InstructorEmbedding'

Error position:
org.jkiss.dbeaver.model.sql.DBSQLException: SQL Error [XX000]: ERROR: Traceback (most recent call last):
  File "transformers.py", line 10, in <module>
 ModuleNotFoundError: No module named 'InstructorEmbedding'
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:133)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:615)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$2(SQLQueryJob.java:506)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:194)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:525)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:977)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:4155)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:123)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:194)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:121)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:5147)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:117)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.postgresql.util.PSQLException: ERROR: Traceback (most recent call last):
  File "transformers.py", line 10, in <module>
 ModuleNotFoundError: No module named 'InstructorEmbedding'
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:307)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:293)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:270)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:266)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:330)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)
	... 12 more

**Comment by SilasMarvin** [comment]
Thank you for the detailed issue! I just tested and am not able to reproduce this error when using the latest version of `pgml` with the latest python dependencies. The latest python dependencies are in the `requirements-linux.txt` file and can be installed by running `pip install -r requirements-linux.txt`. 

What version of `pgml` are you using? You can find this out by running `\dx` in psql.

Can you share the output of `pip freeze`?

**Comment by rmunoz10** [comment]
Hello,
result from pip3 freeze attached. Thanks

[pip3-freeze.txt](https://github.com/user-attachments/files/15805906/pip3-freeze.txt)

**Comment by SilasMarvin** [comment]
You have the right version of sentence transformers. Can you verify that you are using the right version of pgml? You can find this out by running \dx in psql

**Comment by rmunoz10** [comment]
postgres=# \dx
                 List of installed extensions
  Name   | Version |   Schema   |         Description          
---------+---------+------------+------------------------------
 plpgsql | 1.0     | pg_catalog | PL/pgSQL procedural language
(1 row)

postgres=#

**Comment by rmunoz10** [comment]
mydb=# \dx
                      List of installed extensions
  Name   | Version |   Schema   |              Description              
---------+---------+------------+---------------------------------------
 pgml    | 2.8.2   | pgml       | pgml:  Created by the PostgresML team
 plpgsql | 1.0     | pg_catalog | PL/pgSQL procedural language
(2 rows)

mydb=#

**Comment by rmunoz10** [comment]
Hello,
I re-installed from scratch and now the above sql now returns
"[[{"generated_text": "Three Rings for the Elven-kings under the sky, Seven for the Dwarf-lords in their halls of stone and Eight for the Night Elves in their hearts..."}]]"

Issue seems resolved.

Thanks for the help.
