### ISSUE TITLE
Can Node API be removed from dependency? (Deno support)

### ISSUE THREAD

**Issue by xumx** [postgresml/postgresml#1522]
When trying to load the Javascript SDK (v1.0.3) on Deno serverless environments, I get the following Error. 

```
Error: Node API is not supported in this environment
    at Object.Module._extensions..node (node:module:776:20)
    at Module.load (node:module:654:32)
    at Function.Module._load (node:module:522:12)
    at Module.require (node:module:673:19)
    at require (node:module:787:16)
    at Object.<anonymous> (file:///node_modules/.deno/pgml@1.0.3/node_modules/pgml/index.js:16:16)
    at Object.<anonymous> (file:///node_modules/.deno/pgml@1.0.3/node_modules/pgml/index.js:26:4)
    at Module._compile (node:module:729:34)
    at Object.Module._extensions..js (node:module:743:10)
    at Module.load (node:module:654:32)
```

Given that the pgml has a serverless GPU product, we should expect the client SDK to be runnable on more serverless/edge runtimes.

**Comment by levkk** [comment]
The SDK core is written in Rust to provide a uniform implementation across several languages (JavaScript, Rust, Python, Zig, etc.). To achieve this, we're using [neon](https://github.com/neon-bindings/neon) which uses the Node native extensions API. Therefore, our SDK currently can only run on standard Node.js.

As we build it out more, it's not impossible for us to port it to use Deno, but we would much rather have Deno add support for native Node extensions, as it should if it expects to support the entire JavaScript ecosystem of packages.

We'll keep this issue open in the meantime.

**Comment by xumx** [comment]
Maybe in the future you can consider compiling from Rust to WebAssembly, distributing a WASM bundle could be more universally supported across programming languages & runtimes.
