### ISSUE TITLE
SSL SYSCALL error: EOF detected

### ISSUE THREAD

**Issue by katopz** [postgresml/postgresml#1540]
After follow the guide at last step https://postgresml.org/docs/guides/unified-rag#unified-retrieval-+-reranking-+-text-generation
I got this error after run the query (via Docker)
I think is crash at `pgml.transform`

```
SSL SYSCALL error: EOF detected
The connection to the server was lost. Attempting reset: Failed.
```

CPU 266/300%
Memory used 1.54GB/16GB
GPU RAM used 2GB/24GB

Not sure how to avoid this? Thanks

**Comment by montanalow** [comment]
This is likely due to an OOM on your GPU. Which models are you using?

**Comment by katopz** [comment]
> This is likely due to an OOM on your GPU. Which models are you using?

Exactly as demo `meta-llama/Meta-Llama-3-8B-Instruct`.
Anyway when I try to use `GGUF`.

```
        "model": "second-state/Llama-3-8B-Instruct-GGUF",
        "model_file": "Meta-Llama-3-8B-Instruct-Q4_K_M.gguf"
```
 I got.

```
ERROR:  Traceback (most recent call last):
  File "transformers.py", line 489, in transform
  File "transformers.py", line 455, in create_pipeline
  File "transformers.py", line 217, in __init__
  File "/var/lib/postgresml-python/pgml-venv/lib/python3.10/site-packages/ctransformers/hub.py", line 175, in from_pretrained
    llm = LLM(
  File "/var/lib/postgresml-python/pgml-venv/lib/python3.10/site-packages/ctransformers/llm.py", line 253, in __init__
    raise RuntimeError(
 RuntimeError: Failed to create LLM 'gguf' from '/var/lib/postgresql/.cache/huggingface/hub/models--second-state--Llama-3-8B-Instruct-GGUF/blobs/2d4c2369f29c685f740b0f23b4f8a39fa46221eb21429ef1ffa1b14b1970bb17'.
Time: 263767.216 ms (04:23.767)
```

As I recall, I can run llama3 8B GGUF on `RTX4090` via `llama.cpp` just fine.

Thanks

**Comment by fatihsazan** [comment]
hi katopz, 
did you solve your problem? 
I am having the same problem.

**Comment by SilasMarvin** [comment]
Closing this as the original document is gone and we are having no known issues with pgml.transform. If this is still an issue please open another issue with the query you are running. Thank you!
