### ISSUE TITLE
Problem with example given on home page via Docker

### ISSUE THREAD

**Issue by cwbeck** [postgresml/postgresml#1657]
Unable to access the model using the above. I can't find a way to login to huggingface either. Is this a bug?

```
postgresml=# SELECT pgml.transform_stream(
  task   => '{
    "task": "text-generation",
    "model": "meta-llama/Meta-Llama-3.1-8B-Instruct"
  }'::JSONB,
  input  => 'AI is going to',
  args   => '{
    "max_new_tokens": 100
  }'::JSONB
);
ERROR:  Traceback (most recent call last):
  File "transformers.py", line 489, in transform
  File "transformers.py", line 458, in create_pipeline
  File "transformers.py", line 315, in __init__
  File "/var/lib/postgresml-python/pgml-venv/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 523, in from_pretrained
    config, kwargs = AutoConfig.from_pretrained(
  File "/var/lib/postgresml-python/pgml-venv/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 928, in from_pretrained
    config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/var/lib/postgresml-python/pgml-venv/lib/python3.10/site-packages/transformers/configuration_utils.py", line 631, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/var/lib/postgresml-python/pgml-venv/lib/python3.10/site-packages/transformers/configuration_utils.py", line 686, in _get_config_dict
    resolved_config_file = cached_file(
  File "/var/lib/postgresml-python/pgml-venv/lib/python3.10/site-packages/transformers/utils/hub.py", line 416, in cached_file
    raise EnvironmentError(
 OSError: You are trying to access a gated repo.
Make sure to have access to it at https://huggingface.co/meta-llama/Meta-Llama-3.1-8B-Instruct.
401 Client Error. (Request ID: Root=1-6749e970-201580bd0968fd946cf1cb7b;ca75fe4d-4f2c-481f-8013-b956b9eb6c89)

Cannot access gated repo for url https://huggingface.co/meta-llama/Meta-Llama-3.1-8B-Instruct/resolve/main/config.json.
Access to model meta-llama/Llama-3.1-8B-Instruct is restricted. You must have access to it and be authenticated to access it. Please log in.
postgresml=# 
```

**Comment by montanalow** [comment]
This is a dup of #1617
