### ISSUE TITLE
【envirment error】numpy import error

### ISSUE THREAD

**Issue by frg01** [postgresml/postgresml#1658]
1. I installed the pgml extension and exec sql ,but it's error.
```
postgres=# INSERT INTO star_wars_quotes (quote)
VALUES
    ('I find your lack of faith disturbing'),
    ('I''ve got a bad feeling about this.'),
    ('Do or do not, there is no try.');
ERROR:  Traceback (most recent call last):
  File "transformers.py", line 10, in <module>
  File "/var/lib/postgresml-python/pgml-venv/lib/python3.11/site-packages/datasets/__init__.py", line 22, in <module>
    from .arrow_dataset import Dataset
  File "/var/lib/postgresml-python/pgml-venv/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 58, in <module>
    import numpy as np
  File "/var/lib/postgresml-python/pgml-venv/lib/python3.11/site-packages/numpy/__init__.py", line 135, in <module>
    raise ImportError(msg) from e
 ImportError: Error importing numpy: you should not try to import numpy from
        its source directory; please exit the numpy source tree, and relaunch
        your python interpreter from there.
```

2. check pgml-venv ,test numpy 
```
(pgml-venv) postgres@bigmathdev1:~$ pip show numpy 
Location: /var/lib/postgresql/postgresml/pgml-extension/pgml-venv/lib/python3.11/site-packages
Requires: 
Required-by: accelerate, auto_gptq, bitsandbytes, catboost, contourpy, datasets, deepspeed, evaluate, gekko, langchain, lightgbm, matplotlib, numba, outlines, pandas, peft, pyarrow, sacrebleu, scikit-learn, scipy, sentence-transformers, torchvision, transformers, trl, vllm, xformers, xgboost


(pgml-venv) postgres@bigmathdev1:~$ python 
Python 3.11.10 (main, Sep  7 2024, 18:35:41) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> print(np.__version__) 
1.26.4
>>> 
```

3. check postgresql.conf 
```
shared_preload_libraries = 'pgml,pg_stat_statements'    # (change requires restart)
pgml.venv = '/var/lib/postgresql/postgresml/pgml-extension/pgml-venv'
```

how to resolve this problem please ?

**Comment by SilasMarvin** [comment]
This should be a resolved issue now. If this is still a problem, please reopen it.
