### ISSUE TITLE
failed to get `linfa` as a dependency of package `pgml v2.1.2 (/app)`

### ISSUE THREAD

**Issue by Niba-nazar** [postgresml/postgresml#499]
Hi,

I am trying to build a docker image only for pgml-extension. Am getting error at 'RUN cargo pgx package', am trying to build this on postgres13 and debian 10.

````
Step 30/35 : RUN cargo pgx package
 ---> Running in 48fc7645f156
Error:
   0: couldn't get cargo metadata
   1: `cargo metadata` exited with an error:     Updating crates.io index
          Updating git repository `https://github.com/postgresml/lightgbm-rs`
          Updating git submodule `https://github.com/microsoft/LightGBM/`
          Updating git submodule `https://gitlab.com/libeigen/eigen.git`
          Updating git submodule `https://github.com/lemire/fast_double_parser.git`
          Updating git submodule `https://github.com/abseil/abseil-cpp.git`
          Updating git submodule `https://github.com/google/double-conversion.git`
          Updating git submodule `https://github.com/fmtlib/fmt.git`
          Updating git submodule `https://github.com/boostorg/compute`
      error: failed to get `linfa` as a dependency of package `pgml v2.1.2 (/app)`

      Caused by:
        failed to load source for dependency `linfa`

      Caused by:
        Unable to update /app/deps/linfa

      Caused by:
        failed to read `/app/deps/linfa/Cargo.toml`

      Caused by:
        No such file or directory (os error 2)


Location:
   /var/lib/postgresql/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-pgx-0.6.0/src/metadata.rs:23

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ SPANTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

   0: cargo_pgx::command::package::execute
      at /var/lib/postgresql/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-pgx-0.6.0/src/command/package.rs:50

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```

**Comment by solidsnack** [comment]
What do you see with `RUST_BACKTRACE=1`? For example:

```bash
RUST_BACKTRACE=1 cargo pgx package
```

**Comment by levkk** [comment]
You need to get the git submodules:

```
git submodule update --init --recursive
```

**Comment by Niba-nazar** [comment]
@solidsnack , this is wat am getting:

```
Step 30/35 : RUN RUST_BACKTRACE=1 cargo pgx package
 ---> Running in 10cc02068571
Error:
   0: couldn't get cargo metadata
   1: `cargo metadata` exited with an error:     Updating crates.io index
          Updating git repository `https://github.com/postgresml/lightgbm-rs`
          Updating git submodule `https://github.com/microsoft/LightGBM/`
          Updating git submodule `https://gitlab.com/libeigen/eigen.git`
          Updating git submodule `https://github.com/lemire/fast_double_parser.git`
          Updating git submodule `https://github.com/abseil/abseil-cpp.git`
          Updating git submodule `https://github.com/google/double-conversion.git`
          Updating git submodule `https://github.com/fmtlib/fmt.git`
          Updating git submodule `https://github.com/boostorg/compute`
      error: failed to get `linfa` as a dependency of package `pgml v2.1.2 (/app)`

      Caused by:
        failed to load source for dependency `linfa`

      Caused by:
        Unable to update /app/deps/linfa

      Caused by:
        failed to read `/app/deps/linfa/Cargo.toml`

      Caused by:
        No such file or directory (os error 2)


Location:
   /var/lib/postgresql/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-pgx-0.6.0/src/metadata.rs:23

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ SPANTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

   0: cargo_pgx::command::package::execute
      at /var/lib/postgresql/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-pgx-0.6.0/src/command/package.rs:50

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                                ⋮ 3 frames hidden ⋮
   4: cargo_pgx::metadata::metadata::h2ce863f24d4c3e52
      at <unknown source file>:<unknown line>
   5: <cargo_pgx::command::pgx::CargoPgxSubCommands as cargo_pgx::CommandExecute>::execute::h2d2d362dffb4a325
      at <unknown source file>:<unknown line>
   6: cargo_pgx::main::had76bcf35807e6a9
      at <unknown source file>:<unknown line>
   7: std::sys_common::backtrace::__rust_begin_short_backtrace::h296b02e42be24724
      at <unknown source file>:<unknown line>
   8: std::rt::lang_start::{{closure}}::h111f092e3ef35c53
      at <unknown source file>:<unknown line>
   9: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hb69be6e0857c6cfb
      at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/ops/function.rs:283
  10: std::panicking::try::do_call::h396dfc441ee9c786
      at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:492
  11: std::panicking::try::h6cdda972d28b3a4f
      at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:456
  12: std::panic::catch_unwind::h376039ec264e8ef9
      at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panic.rs:137
  13: std::rt::lang_start_internal::{{closure}}::hc94720ca3d4cb727
      at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/rt.rs:148
  14: std::panicking::try::do_call::h2422fb95933fa2d5
      at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:492
  15: std::panicking::try::h488286b5ec8333ff
      at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:456
  16: std::panic::catch_unwind::h81636549836d2a25
      at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panic.rs:137
  17: std::rt::lang_start_internal::h6ba1bb743c1e9df9
      at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/rt.rs:148
  18: main<unknown>
      at <unknown source file>:<unknown line>
  19: __libc_start_main<unknown>
      at <unknown source file>:<unknown line>
  20: _start<unknown>
      at <unknown source file>:<unknown line>

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
Run with RUST_BACKTRACE=full to include source snippets.
The command '/bin/sh -c RUST_BACKTRACE=1 cargo pgx package' returned a non-zero code: 1

```

**Comment by Niba-nazar** [comment]
@levkk , still the same

**Comment by Niba-nazar** [comment]
I have managed to rsolve the above issue, however getting this error now:
```
  -- Installing: /app/target/release/build/xgboost-sys-36ddfa418e250aa0/out/lib/cmake/xgboost/xgboost-config-version.cmake
  -- Installing: /app/target/release/build/xgboost-sys-36ddfa418e250aa0/out/lib/pkgconfig/xgboost.pc
  cargo:root=/app/target/release/build/xgboost-sys-36ddfa418e250aa0/out

  --- stderr
  CMake Warning:
    Manually-specified variables were not used by the project:

      CMAKE_ASM_COMPILER
      CMAKE_ASM_FLAGS


  /app/target/release/build/xgboost-sys-36ddfa418e250aa0/out/xgboost/include/xgboost/c_api.h:12:10: fatal error: 'cstdio' file not found
  thread 'main' panicked at 'Unable to generate bindings.: ClangDiagnostic("/app/target/release/build/xgboost-sys-36ddfa418e250aa0/out/xgboost/include/xgboost/c_api.h:12:10: **fatal error: 'cstdio' file not found\n")',** /var/lib/postgresql/.cargo/git/checkouts/rust-xgboost-2a15eaf65071c283/8f3a8fb/xgboost-sys/build.rs:53:10
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
The command '/bin/sh -c cargo pgx package' returned a non-zero code: 1
```

**Comment by levkk** [comment]
```
fatal error: 'cstdio' file not found
```
Looks like your system is missing libc++ headers:

```
sudo apt-get install build-essential libstdc++6
```

**Comment by Niba-nazar** [comment]
Thank you @levkk Let me try that.


As I already mentioned I tried to build the deb file for pgml using debian 10 and postgres13. I was able to build the docker image using the Dockerfile as follows:
```
FROM debian:buster

RUN set -ex \
    && sed -i -- 's/# deb-src/deb-src/g' /etc/apt/sources.list \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
               build-essential \
               curl \
               cdbs \
               devscripts \
               equivs \
               fakeroot \
    && apt-get clean \
    && rm -rf /tmp/* /var/tmp/*



ARG PGVERSION=13
ARG DEBIAN_FRONTEND=noninteractive
ARG PACKAGE_VERSION=2.0.0
ARG PACKAGE_PYTHON=true
ARG PACKAGE_CUDA=false
ENV TZ=Etc/UTC


# PostgresSQL

RUN apt-get install wget -y && apt-get install git -y
RUN wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -
RUN  sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt buster-pgdg main" > /etc/apt/sources.list.d/pgdg.list'


# CMake


RUN apt-get install -y build-essential libboost-all-dev pkg-config
RUN apt-get install -y --no-install-recommends curl wget

ADD https://github.com/Kitware/CMake/releases/download/v3.18.4/cmake-3.18.4-Linux-x86_64.sh /cmake-3.18.4-Linux-x86_64.sh
RUN mkdir /opt/cmake
RUN sh /cmake-3.18.4-Linux-x86_64.sh --prefix=/opt/cmake --skip-license
RUN ln -s /opt/cmake/bin/cmake /usr/local/bin/cmake



# Get cppcheck dependencies from stable; that's good enough
RUN echo "deb-src http://deb.debian.org/debian buster main" >> /etc/apt/sources.list
RUN apt-get update

RUN apt-get update && apt-get install postgresql-${PGVERSION} libopenblas-dev cmake postgresql-server-dev-${PGVERSION} pkg-config libssl-dev build-essential libclang-dev clang libpython3-dev python3-dev -y

# CUDA
#COPY docker/install_cuda.sh install_cuda.sh
#RUN bash install_cuda.sh
RUN wget https://developer.download.nvidia.com/compute/cuda/repos/debian10/x86_64/cuda-keyring_1.0-1_all.deb

USER postgres


# Install Rust
RUN curl https://sh.rustup.rs -sSf | sh -s -- -y
ENV PATH="/var/lib/postgresql/.cargo/bin:${PATH}"

# Install tcdi/pgx
RUN cargo install cargo-pgx --version 0.5.6
RUN cargo pgx init --pg${PGVERSION} /usr/bin/pg_config


COPY --chown=postgres:postgres . /app
WORKDIR /app


# cargo pgx package command ignores --no-default-features sadly, so we
# have to have a separate Cargo.toml without Python. No big deal.
# Make sure to diff it and update it if you change the main Cargo.toml.
ENV PACKAGE_PYTHON=${PACKAGE_PYTHON}
RUN bash -c 'if [[ "${PACKAGE_PYTHON}" == "false" ]]; then cp docker/Cargo.toml.no-python Cargo.toml; fi'

ENV PACKAGE_CUDA=${PACKAGE_CUDA}
RUN bash -c 'if [[ "${PACKAGE_CUDA}" == "true" ]]; then cp docker/Cargo.toml.cuda Cargo.toml; fi'

# Build and upload package to S3
ENV CUDACXX=/usr/local/cuda/bin/nvcc
RUN cargo pgx package


# Deb file goes here, mount it on your local system
VOLUME /output
USER root

ENV PACKAGE_VERSION=$PACKAGE_VERSION
ENV OUTPUT_DIR=/output

# Run
ENTRYPOINT ["bash", "docker/build_ubuntu_deb.sh", "/output"]
```

also the docker/build_debian_deb.sh is as follows:
```
#!/bin/bash
#
# Build a .deb for the Postgres and Debian version.
#

PACKAGE_VERSION=${PACKAGE_VERSION:-0.0.0}
OUTPUT_DIR=${OUTPUT_DIR:-"."}

if [[ $(uname -a) == *"aarch64"* ]]; then
    ARCH="arm64"
else
    ARCH="amd64"
fi

PGVERSION=$(pg_config | grep "VERSION")

if [[ $PGVERSION == *"12."* ]]; then
    PGVERSION="12"
elif [[ $PGVERSION == *"13."* ]]; then
    PGVERSION="13"
elif [[ $PGVERSION == *"14."* ]]; then
    PGVERSION="14"
elif [[ $PGVERSION == *"11."* ]]; then
    PGVERSION="11"
elif [[ $PGVERSION == *"10."* ]]; then
    PGVERSION="10"
else
    echo "Unknown PostgreSQL version detected: ${PGVERSION}"
    exit 1
fi

TARGET="target/release/pgml-pg${PGVERSION}"
#DEBIAN_VERSION=$(lsb_release -a | grep Release | awk '{ print $2 }')
DEBIAN_VERSION=$(cat /etc/debian_version)


ls -R ${TARGET}

mkdir -p ${TARGET}/DEBIAN
cp control ${TARGET}/DEBIAN/control

# Save version and arch.
sed -i "s/PGVERSION/${PGVERSION}/g" ${TARGET}/DEBIAN/control
sed -i "s/PACKAGE_VERSION/${PACKAGE_VERSION}/g" ${TARGET}/DEBIAN/control
sed -i "s/ARCH/${ARCH}/g" ${TARGET}/DEBIAN/control

# Show me what we got.
cat ${TARGET}/DEBIAN/control

PACKAGE=postgresql-pgml-${PGVERSION}_${PACKAGE_VERSION}-debian${DEBIAN_VERSION}_${ARCH}


# Build the debian package
dpkg-deb --build ${TARGET} $OUTPUT_DIR/${PACKAGE}
```

However, the container is keep on restarting, something is wrong while am trying to build the .deb file. Could you pls have a look into this and let me know where am going wrong?

**Comment by montanalow** [comment]
Closing as stale, I believe the current docker image should address.
