### ISSUE TITLE
Can't run ggml example: KeyError: 'mpt'

### ISSUE THREAD

**Issue by tarasglek** [postgresml/postgresml#803]
from https://postgresml.org/blog/announcing-gptq-and-ggml-quantized-llm-support-for-huggingface-transformers
```
pgml_mkfz47pz3xl8o41=> SELECT pgml.transform(
pgml_mkfz47pz3xl8o41(>     task => '{
pgml_mkfz47pz3xl8o41'>       "task": "text-generation",
pgml_mkfz47pz3xl8o41'>       "model": "TheBloke/MPT-7B-Storywriter-GGML",
pgml_mkfz47pz3xl8o41'>       "model_file": "mpt-7b-storywriter.ggmlv3.q8_0.bin"
pgml_mkfz47pz3xl8o41'>     }'::JSONB,
pgml_mkfz47pz3xl8o41(>     inputs => ARRAY[
pgml_mkfz47pz3xl8o41(>         'Once upon a time,'
pgml_mkfz47pz3xl8o41(>     ],
pgml_mkfz47pz3xl8o41(>     args => '{"max_new_tokens": 32}'::JSONB
pgml_mkfz47pz3xl8o41(> );
ERROR:  Traceback (most recent call last):
  File "", line 93, in transform
  File "/var/lib/postgresml/pgml-venv/lib/python3.10/site-packages/transformers/pipelines/__init__.py", line 705, in pipeline
    config = AutoConfig.from_pretrained(model, _from_pipeline=task, **hub_kwargs, **model_kwargs)
  File "/var/lib/postgresml/pgml-venv/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 940, in from_pretrained
    config_class = CONFIG_MAPPING[config_dict["model_type"]]
  File "/var/lib/postgresml/pgml-venv/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 655, in __getitem__
    raise KeyError(key)
 KeyError: 'mpt'
```

**Comment by montanalow** [comment]
This has been fixed with an update to dependencies in the cloud.
