### ISSUE TITLE
llama examples don't work on on postgresml serverless

### ISSUE THREAD

**Issue by tarasglek** [postgresml/postgresml#804]
https://postgresml.org/blog/announcing-gptq-and-ggml-quantized-llm-support-for-huggingface-transformers
```
pgml_mkfz47pz3xl8o41=> SELECT pgml.transform(
pgml_mkfz47pz3xl8o41(>     task => '{
pgml_mkfz47pz3xl8o41'>       "task": "text-generation",
pgml_mkfz47pz3xl8o41'>       "model": "TheBloke/robin-7B-v2-GGML",
pgml_mkfz47pz3xl8o41'>       "model_type": "llama"
pgml_mkfz47pz3xl8o41'>     }'::JSONB,
pgml_mkfz47pz3xl8o41(>     inputs => ARRAY[
pgml_mkfz47pz3xl8o41(>         'Once upon a time,'
pgml_mkfz47pz3xl8o41(>     ],
pgml_mkfz47pz3xl8o41(>     args => '{"max_new_tokens": 32}'::JSONB
pgml_mkfz47pz3xl8o41(> );
ERROR:  Traceback (most recent call last):
  File "", line 93, in transform
  File "/var/lib/postgresml/pgml-venv/lib/python3.10/site-packages/transformers/pipelines/__init__.py", line 705, in pipeline
    config = AutoConfig.from_pretrained(model, _from_pipeline=task, **hub_kwargs, **model_kwargs)
  File "/var/lib/postgresml/pgml-venv/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 928, in from_pretrained
    config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/var/lib/postgresml/pgml-venv/lib/python3.10/site-packages/transformers/configuration_utils.py", line 574, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/var/lib/postgresml/pgml-venv/lib/python3.10/site-packages/transformers/configuration_utils.py", line 629, in _get_config_dict
    resolved_config_file = cached_file(
  File "/var/lib/postgresml/pgml-venv/lib/python3.10/site-packages/transformers/utils/hub.py", line 463, in cached_file
    raise EnvironmentError(
 OSError: TheBloke/robin-7B-v2-GGML does not appear to have a file named config.json. Checkout 'https://huggingface.co/TheBloke/robin-7B-v2-GGML/main' for available files.
```

**Comment by danieljose** [comment]
Works for me. 
Have you done this?
https://postgresml.org/blog/announcing-gptq-and-ggml-quantized-llm-support-for-huggingface-transformers
You'll need to update to PostgresML 2.6.0 or later to use GPTQ or GGML. You will need to update your Python dependencies for PostgresML to take advantage of these new capabilities. AutoGPTQ also provides prebuilt wheels for Python if you're having trouble installing the pip package which builds it from source. They maintain a list of wheels [available for download](https://github.com/PanQiWei/AutoGPTQ/releases) on GitHub.

pip install -r requirements.txt

**Comment by levkk** [comment]
Fixed! Thanks for reporting this. You can run `ALTER EXTENSION pgml UPDATE` on your database and everything should work.
