### ISSUE TITLE
Error while starting dashboard

### ISSUE THREAD

**Issue by zed92** [postgresml/postgresml#867]
Hi, 
when i start the dashboard container on  windows 10 i get the following error message in docker and the starting process exited:

2023-07-26 18:58:32    Compiling pgml-dashboard v2.5.1 (/app)
2023-07-26 18:58:32    Compiling zoomies v0.1.0 (https://github.com/HyperparamAI/zoomies.git?branch=master#c185ca0d)
2023-07-26 18:58:32    Compiling dotenv v0.15.0
2023-07-26 18:58:32 error: failed to run custom build command for `pgml-dashboard v2.5.1 (/app)`
2023-07-26 18:58:32 
2023-07-26 18:58:32 Caused by:
2023-07-26 18:58:32   process didn't exit successfully: `/app/target/debug/build/pgml-dashboard-7842db221c702b95/build-script-build` (exit status: 101)
2023-07-26 18:58:32   --- stdout
2023-07-26 18:58:32   cargo:rerun-if-changed=migrations
2023-07-26 18:58:32   cargo:rustc-env=GIT_SHA=
2023-07-26 18:58:32 
2023-07-26 18:58:32   --- stderr
2023-07-26 18:58:32   thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', build.rs:21:10
2023-07-26 18:58:32   note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2023-07-26 18:58:32 warning: build failed, waiting for other jobs to finish...
2023-07-26 18:59:08    Compiling pgml-dashboard v2.5.1 (/app)
2023-07-26 18:59:08 error: failed to run custom build command for `pgml-dashboard v2.5.1 (/app)`
2023-07-26 18:59:08 
2023-07-26 18:59:08 Caused by:
2023-07-26 18:59:08   process didn't exit successfully: `/app/target/debug/build/pgml-dashboard-7842db221c702b95/build-script-build` (exit status: 101)
2023-07-26 18:59:08   --- stdout
2023-07-26 18:59:08   cargo:rerun-if-changed=migrations
2023-07-26 18:59:08   cargo:rustc-env=GIT_SHA=
2023-07-26 18:59:08 
2023-07-26 18:59:08   --- stderr
2023-07-26 18:59:08   thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', build.rs:21:10
2023-07-26 18:59:08   note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2023-07-26 18:59:11    Compiling pgml-dashboard v2.5.1 (/app)
2023-07-26 18:59:11 error: failed to run custom build command for `pgml-dashboard v2.5.1 (/app)`
2023-07-26 18:59:11 
2023-07-26 18:59:11 Caused by:
2023-07-26 18:59:11   process didn't exit successfully: `/app/target/debug/build/pgml-dashboard-7842db221c702b95/build-script-build` (exit status: 101)
2023-07-26 18:59:11   --- stdout
2023-07-26 18:59:11   cargo:rerun-if-changed=migrations
2023-07-26 18:59:11   cargo:rustc-env=GIT_SHA=
2023-07-26 18:59:11 
2023-07-26 18:59:11   --- stderr
2023-07-26 18:59:11   thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', build.rs:21:10
2023-07-26 18:59:11   note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2023-07-26 19:01:58    Compiling pgml-dashboard v2.5.1 (/app)
2023-07-26 19:01:58 error: failed to run custom build command for `pgml-dashboard v2.5.1 (/app)`
2023-07-26 19:01:58 
2023-07-26 19:01:58 Caused by:
2023-07-26 19:01:58   process didn't exit successfully: `/app/target/debug/build/pgml-dashboard-7842db221c702b95/build-script-build` (exit status: 101)
2023-07-26 19:01:58   --- stdout
2023-07-26 19:01:58   cargo:rerun-if-changed=migrations
2023-07-26 19:01:58   cargo:rustc-env=GIT_SHA=
2023-07-26 19:01:58 
2023-07-26 19:01:58   --- stderr
2023-07-26 19:01:58   thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', build.rs:21:10
2023-07-26 19:01:58   note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2023-07-26 19:03:56    Compiling pgml-dashboard v2.5.1 (/app)
2023-07-26 19:03:56 error: failed to run custom build command for `pgml-dashboard v2.5.1 (/app)`
2023-07-26 19:03:56 
2023-07-26 19:03:56 Caused by:
2023-07-26 19:03:56   process didn't exit successfully: `/app/target/debug/build/pgml-dashboard-7842db221c702b95/build-script-build` (exit status: 101)
2023-07-26 19:03:56   --- stdout
2023-07-26 19:03:56   cargo:rerun-if-changed=migrations
2023-07-26 19:03:56   cargo:rustc-env=GIT_SHA=
2023-07-26 19:03:56 
2023-07-26 19:03:56   --- stderr
2023-07-26 19:03:56   thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', build.rs:21:10
2023-07-26 19:03:56   note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2023-07-26 19:17:45    Compiling pgml-dashboard v2.5.1 (/app)
2023-07-26 19:17:45 error: failed to run custom build command for `pgml-dashboard v2.5.1 (/app)`
2023-07-26 19:17:45 
2023-07-26 19:17:45 Caused by:
2023-07-26 19:17:45   process didn't exit successfully: `/app/target/debug/build/pgml-dashboard-7842db221c702b95/build-script-build` (exit status: 101)
2023-07-26 19:17:45   --- stdout
2023-07-26 19:17:45   cargo:rerun-if-changed=migrations
2023-07-26 19:17:45   cargo:rustc-env=GIT_SHA=
2023-07-26 19:17:45 
2023-07-26 19:17:45   --- stderr
2023-07-26 19:17:45   thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', build.rs:21:10
2023-07-26 19:17:45   note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2023-07-26 20:49:25    Compiling pgml-dashboard v2.5.1 (/app)
2023-07-26 20:49:25 error: failed to run custom build command for `pgml-dashboard v2.5.1 (/app)`
2023-07-26 20:49:25 
2023-07-26 20:49:25 Caused by:
2023-07-26 20:49:25   process didn't exit successfully: `/app/target/debug/build/pgml-dashboard-7842db221c702b95/build-script-build` (exit status: 101)
2023-07-26 20:49:25   --- stdout
2023-07-26 20:49:25   cargo:rerun-if-changed=migrations
2023-07-26 20:49:25   cargo:rustc-env=GIT_SHA=
2023-07-26 20:49:25 
2023-07-26 20:49:25   --- stderr
2023-07-26 20:49:25   thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', build.rs:21:10
2023-07-26 20:49:25   note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2023-07-26 21:15:41    Compiling pgml-dashboard v2.5.1 (/app)
2023-07-26 21:15:41 error: failed to run custom build command for `pgml-dashboard v2.5.1 (/app)`
2023-07-26 21:15:41 
2023-07-26 21:15:41 Caused by:
2023-07-26 21:15:41   process didn't exit successfully: `/app/target/debug/build/pgml-dashboard-7842db221c702b95/build-script-build` (exit status: 101)
2023-07-26 21:15:41   --- stdout
2023-07-26 21:15:41   cargo:rerun-if-changed=migrations
2023-07-26 21:15:41   cargo:rustc-env=GIT_SHA=
2023-07-26 21:15:41 
2023-07-26 21:15:41   --- stderr
2023-07-26 21:15:41   thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', build.rs:21:10
2023-07-26 21:15:41   note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2023-07-26 22:07:58    Compiling pgml-dashboard v2.5.1 (/app)
2023-07-26 22:07:58 error: failed to run custom build command for `pgml-dashboard v2.5.1 (/app)`
2023-07-26 22:07:58 
2023-07-26 22:07:58 Caused by:
2023-07-26 22:07:58   process didn't exit successfully: `/app/target/debug/build/pgml-dashboard-7842db221c702b95/build-script-build` (exit status: 101)
2023-07-26 22:07:58   --- stdout
2023-07-26 22:07:58   cargo:rerun-if-changed=migrations
2023-07-26 22:07:58   cargo:rustc-env=GIT_SHA=
2023-07-26 22:07:58 
2023-07-26 22:07:58   --- stderr
2023-07-26 22:07:58   thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', build.rs:21:10
2023-07-26 22:07:58   note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2023-07-26 22:08:19    Compiling pgml-dashboard v2.5.1 (/app)
2023-07-26 22:08:19 error: failed to run custom build command for `pgml-dashboard v2.5.1 (/app)`
2023-07-26 22:08:19 
2023-07-26 22:08:19 Caused by:
2023-07-26 22:08:19   process didn't exit successfully: `/app/target/debug/build/pgml-dashboard-7842db221c702b95/build-script-build` (exit status: 101)
2023-07-26 22:08:19   --- stdout
2023-07-26 22:08:19   cargo:rerun-if-changed=migrations
2023-07-26 22:08:19   cargo:rustc-env=GIT_SHA=
2023-07-26 22:08:19 
2023-07-26 22:08:19   --- stderr
2023-07-26 22:08:19   thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', build.rs:21:10
2023-07-26 22:08:19   note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2023-07-26 22:19:22    Compiling pgml-dashboard v2.5.1 (/app)
2023-07-26 22:19:22 error: failed to run custom build command for `pgml-dashboard v2.5.1 (/app)`
2023-07-26 22:19:22 
2023-07-26 22:19:22 Caused by:
2023-07-26 22:19:22   process didn't exit successfully: `/app/target/debug/build/pgml-dashboard-7842db221c702b95/build-script-build` (exit status: 101)
2023-07-26 22:19:22   --- stdout
2023-07-26 22:19:22   cargo:rerun-if-changed=migrations
2023-07-26 22:19:22   cargo:rustc-env=GIT_SHA=
2023-07-26 22:19:22 
2023-07-26 22:19:22   --- stderr
2023-07-26 22:19:22   thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', build.rs:21:10
2023-07-26 22:19:22   note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

If you need more information please let me know.
Thanks for your help.

**Comment by levkk** [comment]
If you're just looking to try out PostgresML, try our new Docker image: https://postgresml.org/docs/guides/setup/quick_start_with_docker

If you want to install the dashboard locally, try our instructions on https://postgresml.org/docs/guides/setup/v2/installation#header-23

I'll take a look at what's going on the dashboard Docker container and see what I can find in the meantime.

**Comment by zed92** [comment]
Thanks for your answer and your help.
Is there an issue with windows? I am using Windows with linux subsystem if this helps you for troubleshooting.
I can only find a setup for macOS and Linux? I think there was a guide for windows?

**Comment by levkk** [comment]
Windows just uses WSL (Windows Subsystem for Linux). If you use Ubuntu 22.04 there, you can follow the Ubuntu instructions. Also, the Docker image should work on Windows as long as you're using the WSL2 backend.

**Comment by zed92** [comment]
Hi
i just cloned the latest version and started it with 'docker-compose up' and still got the following error while the dashboard container was starting. 

<img width="1043" alt="image" src="https://github.com/postgresml/postgresml/assets/40694528/62b8d04c-3aeb-483f-ac17-1ff7411db9c8">

**Comment by SilasMarvin** [comment]
Are you still having issues with our latest version docker?
